version: "3.8"

services:
  vite-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5173:5173"
      - "4173:4173"
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: sleep infinity
